version: '3'

services:
  history-etl:
    image: kinecosystem/history-collector
    environment:
      POSTGRES_HOST: 'db'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'kin'
      DB_USER: 'python'
      DB_USER_PASSWORD: '12345'
      KIN_ISSUER: 'GDF42M3IPERQCBLWFEZKQRK77JQ65SCKTU3CW36HZVCX7XX5A5QXZIVK'
      NETWORK_PASSPHRASE: 'Public Global Kin Ecosystem Network ; June 2018'
      MAX_RETRIES: 5
      BUCKET_NAME: 'stellar-core-ecosystem-6145'
      APP_ID:
      CORE_DIRECTORY: ''
      FIRST_FILE: '00203dff'
      LOG_LEVEL: 'INFO'
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432

  sample:
    image: kinecosystem/history-collector-sample
    ports:
      - 3000:3000
    depends_on:
      - db
      - history-etl
